/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-generated.d.ts --config dist/server/wrangler.json --include-runtime false` (hash: a0c9e8f038e35b01e53a5a2dfe4cf554)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	APP_ORIGIN: "https://concertmatch.ticore.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN">> {}
}
