"use client";
import { useState } from "react";
import { ArrowUpRight, Plus, AudioLines, MapPin, Users, Bookmark, ArrowRight, SlidersHorizontal } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
export default function ConcertApp(){
 const [open,setOpen]=useState(false);
 return <><header className="topbar"><a href="/" className="wordmark"><AudioLines/>concertmatch<span className="beta">BETA</span></a><nav><a className="active" href="/">Konzerte finden</a><button onClick={()=>setOpen(true)}>So funktioniert’s <ArrowUpRight size={15}/></button></nav></header>
 <main className="workspace"><section className="page-heading"><div><div className="eyebrow">ANDERER GESCHMACK. GLEICHER ABEND.</div><h1>Wo geht ihr <em>zusammen</em> hin?</h1><p>Findet das Konzert, auf das ihr euch alle freut.</p></div><div className="small-stamp"><AudioLines/><span>Gute Musik.<br/>Bessere Gesellschaft.</span></div></section>
 <div className="workspace-grid"><aside className="sidebar"><div className="panel"><div className="section-label"><span>01</span> EURE RUNDE <Users size={17}/></div><h2>Wer kommt mit?</h2><p className="muted">Lieblingskünstler auswählen, dann die anderen einladen.</p><button className="person-add" onClick={()=>setOpen(true)}><span className="avatar coral">Du</span><span>Dein Musikgeschmack<small>Mit Lieblingskünstlern starten</small></span><Plus size={19}/></button><button className="outline wide" onClick={()=>setOpen(true)}><Plus size={17}/> Gruppe starten</button><div className="privacy-note">Ohne Konto. Euer Link bleibt unter euch.</div></div>
 <div className="panel"><div className="section-label"><span>02</span> EUER RADIUS <MapPin size={17}/></div><label htmlFor="city">Von wo startet ihr?</label><input id="city" defaultValue="Hamburg"/><div className="inline-meta"><span>Maximale Entfernung</span><b>100 km</b></div><div className="range-preview"><i/></div><p className="fine">Entfernung als Luftlinie. Die Fahrt plant ihr selbst.</p></div><figure className="crowd-card"><img src="/crowd.jpg" alt="Menschen vor einer beleuchteten Konzertbühne"/><figcaption>Der beste Platz ist<br/>nebeneinander.</figcaption></figure></aside>
 <section className="results"><div className="results-heading"><div><div className="section-label">EURE KONZERTAUSWAHL</div><h2>Ein Abend für alle.</h2></div><button className="round-button" aria-label="Filter" onClick={()=>setOpen(true)}><SlidersHorizontal size={20}/></button></div><div className="result-tabs"><button className="selected">Alle Konzerte</button><button onClick={()=>setOpen(true)}>Entdeckungen</button><button onClick={()=>setOpen(true)}><Bookmark size={15}/> Merkliste</button></div><div className="start-card"><span className="step-number">1 + 1</span><h2>Euer Match beginnt<br/>mit eurer Musik.</h2><p>Ein paar Lieblingskünstler reichen. Wir finden Gemeinsamkeiten – und Konzerte, die euch auf neue Ideen bringen.</p><button className="primary" onClick={()=>setOpen(true)}>Musikgeschmack hinzufügen <ArrowRight size={18}/></button><div className="start-facts"><span>2–8 Personen</span><span>Mit fairen Empfehlungen</span><span>Ohne Spotify-Pflicht</span></div></div><div className="editorial-note"><span>UNSER ANSATZ</span><p>Nicht einfach der Durchschnitt. Ein gutes Match berücksichtigt jede Person in eurer Runde.</p></div></section></div></main>
 <footer><a className="wordmark" href="/">concertmatch</a><span>Zusammen klingt’s besser.</span><div><a href="/methode">Matching erklärt</a><a href="/datenschutz">Datenschutz</a><a href="/impressum">Impressum</a></div></footer>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Eure Musik. Euer Abend.</DialogTitle><DialogDescription>Wählt eure Lieblingskünstler und ladet eure Freunde ein. Eure gemeinsame Konzertauswahl berücksichtigt euren Musikgeschmack, die Entfernung und euer Budget.</DialogDescription></DialogContent></Dialog></>;
}
